# Railway configuration for option-chain-python

[build]
builder = "nixpacks"

[deploy]
startCommand = "python generate_token.py --install-deps && python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
RAILWAY_ENVIRONMENT = "production"
